import type { NextPage } from 'next'
import Head from 'next/head'
import { useState, useRef } from 'react';
import { Autocomplete, Loader } from '@mantine/core';
import React from 'react';

const Home: NextPage = () => {
  const timeoutRef = useRef<number>(-1);
  const [value, setValue] = useState('');
  const [loading, setLoading] = useState(false);
  const [data, setData] = useState<string[]>([]);

  const handleChange = (val: string) => {
    window.clearTimeout(timeoutRef.current);
    setValue(val);
    setData([]);

    if (val.trim().length === 0 || val.includes('@')) {
      setLoading(false);
    } else {
      setLoading(true);
      timeoutRef.current = window.setTimeout(() => {
        setLoading(false);
        setData(['gmail.com', 'outlook.com', 'yahoo.com'].map((provider) => `${val}@${provider}`));
      }, 1000);
    }
  };

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p>
          Get started by editing{' '}
          <code>pages/index.tsx</code>
        </p>

        <div>
          <Autocomplete
            value={value}
            data={data}
            onChange={handleChange}
            rightSection={loading ? <Loader size={16} /> : null}
            label="Async Autocomplete data"
            placeholder="Your email"
          />
        </div>
      </main>
    </div>
  )
}

export default Home