# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Back

on:
  push:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Build
      working-directory: back
      run: go build -v ./...

    - name: Test
      working-directory: back
      run: go test -v ./...

    - name: Codacy Analysis CLI
      uses: codacy/codacy-analysis-cli-action@v4.2.0
      with:
        project-token: ${{ secrets.CODACY_TOKEN }}
        run-gosec: "true"
        run-staticcheck: "true"
        directory: ./back
