# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Build
      run: go build -v back/...

    - name: Test
      run: go test -v back/...

    - name: Codacy Analysis CLI
      uses: codacy/codacy-analysis-cli-action@v4.2.0
      with:
        project-token: $CODACY_TOKEN
